import { AnimeTheme } from './index';

export const onePieceTheme: AnimeTheme = {
  id: 'one-piece',
  name: 'One Piece',
  description: 'Pirate King — Set sail on the Grand Line',
  emoji: '🏴‍☠️',
  colors: {
    light: {
      background: '40 30% 94%',
      foreground: '220 40% 13%',
      card: '40 25% 97%',
      'card-foreground': '220 40% 13%',
      popover: '40 25% 97%',
      'popover-foreground': '220 40% 13%',
      primary: '220 70% 35%',
      'primary-foreground': '40 30% 96%',
      secondary: '35 20% 88%',
      'secondary-foreground': '220 40% 13%',
      muted: '35 15% 85%',
      'muted-foreground': '220 20% 40%',
      accent: '45 90% 50%',
      'accent-foreground': '220 40% 13%',
      destructive: '0 75% 50%',
      'destructive-foreground': '0 85% 97%',
      border: '35 25% 75%',
      input: '35 25% 75%',
      ring: '220 70% 35%',
      divider: '35 25% 75%',
      'glow-color': '45 85% 55%',
      'noise-opacity': '0.03',
      'theme-accent-1': '45 85% 55%',   // op-gold
      'theme-accent-2': '0 70% 55%',    // op-red
      'theme-accent-3': '40 60% 70%',   // op-straw
      'theme-accent-4': '200 60% 40%',  // op-ocean
      'theme-accent-5': '220 70% 35%',  // op-marine
    },
    dark: {
      background: '222 50% 8%',
      foreground: '40 30% 90%',
      card: '220 35% 13%',
      'card-foreground': '40 30% 90%',
      popover: '220 35% 16%',
      'popover-foreground': '40 30% 90%',
      primary: '45 85% 55%',
      'primary-foreground': '222 50% 8%',
      secondary: '200 40% 20%',
      'secondary-foreground': '40 30% 90%',
      muted: '220 25% 22%',
      'muted-foreground': '40 20% 65%',
      accent: '0 70% 55%',
      'accent-foreground': '40 30% 95%',
      destructive: '0 84% 60%',
      'destructive-foreground': '0 85% 97%',
      border: '45 30% 30%',
      input: '45 30% 30%',
      ring: '45 85% 55%',
      divider: '45 20% 22%',
      'glow-color': '45 85% 55%',
      'noise-opacity': '0.04',
      'theme-accent-1': '45 85% 55%',
      'theme-accent-2': '0 70% 55%',
      'theme-accent-3': '40 60% 70%',
      'theme-accent-4': '200 60% 40%',
      'theme-accent-5': '220 70% 35%',
    },
  },
  fonts: {
    header: "'Playfair Display', serif",
    body: "'Lora', serif",
    mono: "'JetBrains Mono', monospace",
    handwritten: "'Cormorant Garamond', serif",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500;600&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400&display=swap",
  },
  labels: {
    nav: [
      { path: '/', label: 'Crew' },
      { path: '/projects', label: 'Treasure Map' },
      { path: '/blog', label: "Captain's Log" },
    ],
    backLink: 'Return to Port',
    subPageTitles: {
      '/experiences': 'Voyage Log',
      '/projects': 'Treasure Map',
      '/blog': "Captain's Log",
    },
    sections: {
      experience: 'Voyage Log',
      education: 'Training Arc',
      projects: 'Treasure Map',
      skills: 'Devil Fruits & Haki',
      skillsSubtitle: '',
      heatmap: 'Battles Fought',
      heatmapUnit: 'battles',
      heatmapLow: 'Calm',
      heatmapHigh: 'Fierce',
      heatmapCta: 'Join my crew on GitHub',
    },
    viewAll: 'Set Sail',
    status: {
      live: 'Discovered',
      building: 'Charting...',
      'coming-soon': 'Uncharted',
    },
    resume: 'Bounty Poster',
    contact: 'Den Den Mushi',
    footer: {
      quote: "I'm gonna be King of the Pirates!",
      author: 'Monkey D. Luffy',
      crafted: 'Crafted by',
      brandName: 'Nakama Gyan',
      timeLabel: "Ship's Log:",
    },
    skillCategories: {
      Languages: 'Haki Types',
      Frameworks: 'Devil Fruits',
      Tools: 'Weapons',
      Databases: 'Treasure Vaults',
      Other: 'Grand Line Skills',
    },
    bulletChar: '☠',
    projectLinks: {
      github: 'Chart',
      live: 'Explore',
    },
  },
  icons: {
    experience: 'Compass',
    education: 'BookOpen',
    projects: 'Ship',
    skills: 'Anchor',
    themeToggleLight: 'Anchor',
    themeToggleDark: 'Skull',
    resume: 'Skull',
    statusLive: 'Gem',
    statusBuilding: 'Compass',
  },
  textures: {
    watermarkChar: '⊕',
    selectionBg: 'var(--theme-accent-1)',
    selectionColor: '222 50% 8%',
  },
};
